"""Unified API error contract (Sprint 5.20).

Every non-2xx JSON response uses the same envelope:

    {
      "code": "...",
      "message": "...",
      "details": {...} | null,
      "field_errors": [{"field", "code", "message"}],
      "request_id": "req_..." | null
    }

HTTP status semantics are unchanged; only the payload shape is unified.
"""

from __future__ import annotations

import secrets
from typing import Any

from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field


class ApiFieldError(BaseModel):
    model_config = ConfigDict(extra="ignore")

    field: str
    code: str
    message: str


class ApiErrorResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")

    code: str
    message: str
    details: dict[str, Any] | None = None
    field_errors: list[ApiFieldError] = Field(default_factory=list)
    request_id: str | None = None


def new_request_id() -> str:
    return f"req_{secrets.token_hex(8)}"


def api_error_response(
    *,
    status_code: int,
    code: str,
    message: str,
    details: dict[str, Any] | None = None,
    field_errors: list[ApiFieldError] | None = None,
    request_id: str | None = None,
) -> JSONResponse:
    body = ApiErrorResponse(
        code=code,
        message=message,
        details=details,
        field_errors=field_errors or [],
        request_id=request_id,
    )
    return JSONResponse(status_code=status_code, content=body.model_dump(mode="json"))


class ErrorCodes:
    """Centralized error code registry. Categories:
    AUTH_*, PROFILE_*, STRATEGY_*, MEMORY_*, MENU_*, REPLACEMENT_*, REQUEST_*, INTERNAL_*.
    Codes raised inside domain modules (e.g. StrategyValidationError.code) are
    passed through the same envelope.
    """

    # Request / validation
    REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"

    # Auth
    AUTH_REQUIRED = "AUTH_REQUIRED"

    # Profile
    PROFILE_REQUIRED = "PROFILE_REQUIRED"
    PROFILE_INVALID = "PROFILE_INVALID"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"
    PROFILE_STALE = "PROFILE_STALE"
    PROFILE_PROTEIN_REQUIRED = "PROFILE_PROTEIN_REQUIRED"
    PROFILE_PROTEIN_EXCLUDED = "PROFILE_PROTEIN_EXCLUDED"
    PROFILE_ANY_WITH_SPECIFIC_PROTEINS = "PROFILE_ANY_WITH_SPECIFIC_PROTEINS"
    PROFILE_TOO_MANY_CONSTRAINTS = "PROFILE_TOO_MANY_CONSTRAINTS"
    PROFILE_CONSTRAINT_VALUE_EMPTY = "PROFILE_CONSTRAINT_VALUE_EMPTY"
    PROFILE_CONSTRAINT_ID_INVALID = "PROFILE_CONSTRAINT_ID_INVALID"

    # Strategy / preview / conflicts
    STRATEGY_PREVIEW_REQUIRED = "STRATEGY_PREVIEW_REQUIRED"
    STRATEGY_PREVIEW_STALE = "STRATEGY_PREVIEW_STALE"
    STRATEGY_PREVIEW_STALE_BEHAVIOR = "STRATEGY_PREVIEW_STALE_BEHAVIOR"
    STRATEGY_PREVIEW_STALE_LEARNED_PREFERENCES = (
        "STRATEGY_PREVIEW_STALE_LEARNED_PREFERENCES"
    )
    STRATEGY_PREVIEW_INVALID = "STRATEGY_PREVIEW_INVALID"
    STRATEGY_INVALID = "STRATEGY_INVALID"
    STRATEGY_SAVE_FAILED = "STRATEGY_SAVE_FAILED"
    STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
    STRATEGY_NOT_ACTIVE = "STRATEGY_NOT_ACTIVE"
    STRATEGY_VERSION_UNSUPPORTED = "STRATEGY_VERSION_UNSUPPORTED"
    STRATEGY_COMPARE_NOT_AVAILABLE = "STRATEGY_COMPARE_NOT_AVAILABLE"
    STRATEGY_COMPARE_UNSUPPORTED_VERSION = "STRATEGY_COMPARE_UNSUPPORTED_VERSION"
    STRATEGY_COMPARE_FAILED = "STRATEGY_COMPARE_FAILED"
    CONFLICT_NOT_FOUND = "CONFLICT_NOT_FOUND"
    CONFLICT_ACTION_NOT_ALLOWED = "CONFLICT_ACTION_NOT_ALLOWED"
    CONFLICT_RESOLUTION_FAILED = "CONFLICT_RESOLUTION_FAILED"
    CONSTRAINT_NOT_REMOVABLE = "CONSTRAINT_NOT_REMOVABLE"

    # Memory
    MEMORY_SIGNAL_NOT_FOUND = "MEMORY_SIGNAL_NOT_FOUND"
    MEMORY_SIGNAL_NOT_PROMOTABLE = "MEMORY_SIGNAL_NOT_PROMOTABLE"
    MEMORY_SIGNAL_NOT_CONFIRMED = "MEMORY_SIGNAL_NOT_CONFIRMED"
    MEMORY_SIGNAL_ALREADY_PROMOTED = "MEMORY_SIGNAL_ALREADY_PROMOTED"
    MEMORY_PROMOTION_PROFILE_STALE = "MEMORY_PROMOTION_PROFILE_STALE"
    MEMORY_PROMOTION_FAILED = "MEMORY_PROMOTION_FAILED"

    # Menu generation
    MENU_GENERATION_TIMEOUT = "MENU_GENERATION_TIMEOUT"
    MENU_GENERATION_UNAVAILABLE = "MENU_GENERATION_UNAVAILABLE"
    MENU_GENERATION_INVALID = "MENU_GENERATION_INVALID"
    MENU_GENERATION_OUTPUT_TRUNCATED = "MENU_GENERATION_OUTPUT_TRUNCATED"

    # Replacement
    REPLACEMENT_NOT_FOUND = "REPLACEMENT_NOT_FOUND"
    REPLACEMENT_INVALID = "REPLACEMENT_INVALID"
    REPLACEMENT_FAILED = "REPLACEMENT_FAILED"
    REPLACEMENT_PRICE_UNRESOLVED = "REPLACEMENT_PRICE_UNRESOLVED"

    # Durable MenuPlan (Sprint 7.2)
    MENU_PLAN_NOT_FOUND = "MENU_PLAN_NOT_FOUND"
    MENU_PLAN_STALE = "MENU_PLAN_STALE"
    MENU_PLAN_FAILED = "MENU_PLAN_FAILED"

    # Positive outcome events (Sprint 6.5)
    POSITIVE_EVENT_INVALID = "POSITIVE_EVENT_INVALID"
    POSITIVE_EVENT_NOT_ALLOWED = "POSITIVE_EVENT_NOT_ALLOWED"

    # Decision Learning
    LEARNING_RECOMMENDATION_NOT_FOUND = "LEARNING_RECOMMENDATION_NOT_FOUND"
    LEARNING_RECOMMENDATION_NOT_AVAILABLE = "LEARNING_RECOMMENDATION_NOT_AVAILABLE"
    LEARNING_RECOMMENDATION_FAILED = "LEARNING_RECOMMENDATION_FAILED"

    # Learned Preferences (Sprint 9.1)
    LEARNED_PREFERENCE_NOT_FOUND = "LEARNED_PREFERENCE_NOT_FOUND"
    LEARNED_PREFERENCE_NOT_AVAILABLE = "LEARNED_PREFERENCE_NOT_AVAILABLE"
    LEARNED_PREFERENCE_FAILED = "LEARNED_PREFERENCE_FAILED"

    # Dev tools (Sprint 9.5) — never exposed as product features
    DEV_TOOLS_DISABLED = "DEV_TOOLS_DISABLED"
    DEV_RESET_CONFIRM_REQUIRED = "DEV_RESET_CONFIRM_REQUIRED"
    DEV_QA_SCENARIO_UNKNOWN = "DEV_QA_SCENARIO_UNKNOWN"
    DEV_TOOLS_FAILED = "DEV_TOOLS_FAILED"

    # Behavior
    BEHAVIOR_INSIGHT_NOT_FOUND = "BEHAVIOR_INSIGHT_NOT_FOUND"
    BEHAVIOR_INSIGHT_INVALID_TRANSITION = "BEHAVIOR_INSIGHT_INVALID_TRANSITION"
    BEHAVIOR_INSIGHT_NOT_CONFIRMABLE = "BEHAVIOR_INSIGHT_NOT_CONFIRMABLE"
    BEHAVIOR_INSIGHT_NOT_DISMISSIBLE = "BEHAVIOR_INSIGHT_NOT_DISMISSIBLE"
    BEHAVIOR_INSIGHT_NOT_SNOOZABLE = "BEHAVIOR_INSIGHT_NOT_SNOOZABLE"
    BEHAVIOR_INSIGHT_NOT_REVOKABLE = "BEHAVIOR_INSIGHT_NOT_REVOKABLE"
    BEHAVIOR_SNOOZE_DURATION_INVALID = "BEHAVIOR_SNOOZE_DURATION_INVALID"
    BEHAVIOR_INSIGHT_ALREADY_REVOKED = "BEHAVIOR_INSIGHT_ALREADY_REVOKED"
    BEHAVIOR_SNOOZE_FAILED = "BEHAVIOR_SNOOZE_FAILED"
    BEHAVIOR_REVOKE_FAILED = "BEHAVIOR_REVOKE_FAILED"
    BEHAVIOR_SERVICE_UNAVAILABLE = "BEHAVIOR_SERVICE_UNAVAILABLE"
    BEHAVIOR_EVALUATION_FAILED = "BEHAVIOR_EVALUATION_FAILED"
    BEHAVIOR_CONTEXT_UNAVAILABLE = "BEHAVIOR_CONTEXT_UNAVAILABLE"
    BEHAVIOR_RECOMMENDATION_NOT_AVAILABLE = "BEHAVIOR_RECOMMENDATION_NOT_AVAILABLE"
    BEHAVIOR_RECOMMENDATION_ALREADY_APPLIED = "BEHAVIOR_RECOMMENDATION_ALREADY_APPLIED"
    BEHAVIOR_RECOMMENDATION_PROFILE_STALE = "BEHAVIOR_RECOMMENDATION_PROFILE_STALE"
    BEHAVIOR_RECOMMENDATION_FAILED = "BEHAVIOR_RECOMMENDATION_FAILED"
    UNSUPPORTED_APPLIED_BEHAVIOR_VERSION = "UNSUPPORTED_APPLIED_BEHAVIOR_VERSION"

    # Internal
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
